spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jitendraimrb/cloud-config-server
          clone-on-start: true
          
server:
  port: 9296